[package]
name = "speak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.3"
tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1"
